meta:
  engine: 4.1.0
  version: 0.5.0
  author: Daniel Fox
units:
  # For Ergogen - set the default width and height to Choc.
  # Comment out if you're using MX layout, though this only affects the display
  # on the Ergogen site.
  $default_width: cx
  $default_height: cy
  # Proxy spacing variables - Choc (low-profile)
  kx: cx
  ky: cy
  # Proxy spacing variables - MX layout
  # kx: u
  # ky: u
  # Padding
  px: kx + 2
  py: ky + 2
  # Half distance, for movement
  hx: (kx / 2)
  hy: (ky / 2)
  # half padding distance, for movement
  hpx: (px / 2)
  hpy: (py / 2)
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100] # correct anchoring for KiCAD sheet
      key:
        padding: 1ky
        spread: 1kx
        tags:
          cap: true
      rows:
        mod:
          row_net: P113
        bottom:
          row_net: P115
        home:
          row_net: P002
        top:
          row_net: P029
        num:
          row_net: P013
      columns:
        outer:
          rows.mod.skip: true
          key:
            width: 1.5kx
            stagger: 0
            col_net: P020
            tags:
              cap: false
              bigcap: true
        pinky:
          rows.mod.skip: true
          key:
            stagger: 0
            col_net: P022
            spread: 1.25kx
        ring:
          key:
            stagger: 5
            col_net: P024
          rows.mod.col_net: P022
        middle:
          key:
            stagger: 3
            col_net: P100
          rows.mod.col_net: P024
        index:
          key:
            stagger: -3
            col_net: P011
          rows.mod.col_net: P100
        inner:
          rows.mod.skip: true
          key:
            stagger: -3
            col_net: P017
    thumbs:
      key:
        spread: 1ky
        rotate: 90
        tags:
          bigcap: true
      anchor:
        ref: matrix_inner_mod
        shift: [2, -2]
      columns:
        space:
          key:
            height: 1.5kx
            splay: -30
            col_net: P011
            shift: [0.25hpx, -0.75hpy]
        extra:
          key:
            height: 1.5kx
            col_net: P017
            shift: [0.25hpx, -0.75hpy]
      rows:
        cluster:
          row_net: P113
  rotate: 0
  mirror: &mirror
    ref: thumbs_extra_cluster
    distance: 2.5kx
outlines:
  switch_grid:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  keys1u:
    - what: rectangle
      where: cap
      size: [kx-0.5, ky-0.5]
  keys15u:
    - what: rectangle
      where: bigcap
      size: [1.5kx-0.5, ky-0.5]
  keys:
    [keys1u, keys15u]
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_num # Upper-left corner
          shift: [-0.75px, hpy]
        - ref: matrix_middle_num
          shift: [-hpx, hpy]
        - ref: matrix_middle_num
          shift: [hpx, hpy]
        - ref: matrix_inner_num
          shift: [hpx, hpy]
        - ref: matrix_inner_num # Upper-right corner, adding space for electronics
          shift: [hpx + 1px, hpy]
        - ref: thumbs_extra_cluster # Bottmo of thumb cluster bump
          shift: [0.75py, -hpy]
        - ref: thumbs_extra_cluster # Inside cluster
          shift: [-0.75py - 1, -hpx]
        - ref: matrix_ring_mod
          shift: [px - 2, -hpy]
        - ref: matrix_ring_mod
          shift: [-hpx, -hpy]
        - ref: matrix_outer_bottom
          shift: [-0.75px, -hpy]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_outer_num # Upper-left corner
          shift: [-0.75px, hpy]
        - ref: mirror_matrix_middle_num
          shift: [-hpx, hpy]
        - ref: mirror_matrix_middle_num
          shift: [hpx, hpy]
        - ref: mirror_matrix_inner_num
          shift: [hpx, hpy]
        - ref: mirror_matrix_inner_num # Upper-right corner, adding space for electronics
          shift: [hpx + 1px, hpy]
        - ref: mirror_thumbs_extra_cluster # Bottmo of thumb cluster bump
          shift: [0.75py, -hpy]
        - ref: mirror_thumbs_extra_cluster # Inside cluster
          shift: [-0.75py - 1, -hpx]
        - ref: mirror_matrix_ring_mod
          shift: [px - 2, -hpy]
        - ref: mirror_matrix_ring_mod
          shift: [-hpx, -hpy]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.75px, -hpy]
  board_left_keycaps:
    - name: board_left
    - operation: subtract
      name: keys
  board_right_keycaps:
    - name: board_right
    - operation: subtract
      name: keys
  board_left_switch_cutouts:
    - name: board_left
    - operation: subtract
      name: switch_grid
  board_right_switch_cutouts:
    - name: board_right
    - operation: subtract
      name: switch_grid
pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^(?:matrix|thumbs)_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^(?:matrix|thumbs)_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      rotary_knob:
        what: rotary
        params:
          from: P020
          to: P113
          A: P006
          B: GND
          C: P008
        where:
          ref: matrix_inner_home
          shift: [px - 1.5, -hpy + 3]
          rotate: 90
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: down
        where:
          ref: matrix_inner_top
          shift: [px - 2,hpy - 1]
          rotate: -90
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_inner_bottom
          shift: [px, -2]
          rotate: 90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_inner_home
          shift: [1.5px - 2, -4]
          rotate: -90
      # Switch
      battery_switch:
        what: slider
        where:
          ref: matrix_inner_home
          shift: [1.5px - 2, hpy - 4]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # PCB text - CYBERFOX
      front_text: &text
        what: text
        where: &textWhere
          ref: matrix_inner_bottom
          shift: [-hpx + 1, -hpy - 2]
        params: &textParams
          text: "CYBERFOX-60"
          justify: left
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^mirror_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^mirror_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      rotary_knob:
        what: rotary
        params:
          from: P020
          to: P113
          A: P006
          B: GND
          C: P008
        where:
          ref: mirror_matrix_inner_home
          shift: [px - 1.5, -hpy + 3]
          rotate: 270
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: down
        where:
          ref: mirror_matrix_inner_top
          shift: [px - 2,hpy - 1]
          rotate: -270
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_inner_bottom
          shift: [px, -2]
          rotate: 90
        params:
          side: B
          pos: pos
          neg: GND
      # Reset switch
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: mirror_matrix_inner_home
          shift: [1.5px - 2, -4]
          rotate: -90
      # Switch
      battery_switch:
        what: slider
        where:
          ref: mirror_matrix_inner_home
          shift: [1.5px - 2, hpy - 4]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
      # PCB text - CYBERFOX
      front_text: &text
        what: text
        where: &textWhere
          ref: mirror_matrix_inner_bottom
          shift: [-hpx + 1, -hpy - 2]
        params: &textParams
          text: "CYBERFOX-60"
          justify: right
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4
