meta:
  engine: 4.1.0
  version: 0.5.0
  author: Daniel Fox
units:
  # For Ergogen - set the default width and height to Choc.
  # Comment out if you're using MX layout, though this only affects the display
  # on the Ergogen site.
  $default_width: cx
  $default_height: cy
  # Proxy spacing variables - Choc (low-profile)
  kx: cx
  ky: cy
  spacing: 0.75
  # Proxy spacing variables - MX layout
  # kx: u
  # ky: u
  # Padding
  px: kx + 2
  py: ky + 2
  # Half distance, for movement
  hx: (kx / 2)
  hy: (ky / 2)
  # half padding distance, for movement
  hpx: (px / 2)
  hpy: (py / 2)
  # positioning of electric components
  rotary_shift_x: px + 5
  rotary_shift_y: -2
  rotary_diode_shift_x: px + 5
  rotary_diode_shift_y: 6.5
  nice_nano_shift_x: px + 3
  nice_nano_shift_y: py - 2
  nice_view_shift_x: px + 3
  nice_view_shift_y: py - 6
  battery_shift_x: 1.5px + 7
  battery_shift_y: 7 
  reset_shift_x: 4
  reset_shift_y: hpy + 4
  switch_shift_x: 1.5px + 11
  switch_shift_y: py
  text_shift_x: -hpx + 1
  text_shift_y: -hpy - 2
points:
  zones:
    matrix:
      anchor:
        shift: [050, -110] # correct anchoring for KiCAD sheet
      key:
        padding: ky + 2spacing
        spread: kx + 2spacing
        tags:
          cap: true
      rows:
        mod:
          row_net: P7
        bottom:
          row_net: P8
        home:
          row_net: P9
        top:
          row_net: P10
        num:
          row_net: P16
      columns:
        outer:
          rows.mod.skip: true
          key:
            width: 1.5kx
            stagger: 0
            col_net: P14
            tags:
              cap: false
              bigcap: true
        pinky:
          rows.mod.skip: true
          key:
            stagger: 0
            col_net: P15
            spread: 1.175px
        ring:
          rows.mod.col_net: P14
          key:
            stagger: 5
            col_net: P18
        middle:
          rows.mod.col_net: P15
          key:
            stagger: 3
            col_net: P19
        index:
          rows.mod.col_net: P18
          key:
            stagger: -3
            col_net: P20
        inner:
          rows.mod.skip: true
          key:
            stagger: -3
            col_net: P21
    thumbs:
      key:
        padding: ky + 2spacing
        spread: kx + 2spacing
        # spread: 1kx
        rotate: 90
        tags:
          bigcap: true
      anchor:
        ref: matrix_inner_mod
        shift: [10, -2]
      columns:
        space:
          key:
            height: 1.5kx
            splay: -25
            col_net: P19
            shift: [0.25hpx, -0.75hpy]
        extra:
          key:
            height: 1.5kx
            col_net: P20
            shift: [0.25hpx, -0.75hpy]
      rows:
        cluster:
          row_net: P7
  rotate: 0
outlines:
  switch_grid:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  keys1u:
    - what: rectangle
      where: cap
      size: [kx-0.5, ky-0.5]
  keys15u:
    - what: rectangle
      where: bigcap
      size: [1.5kx-0.5, ky-0.5]
  keys:
    [keys1u, keys15u]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_num # Upper-left corner
          shift: [-0.75px, hpy]
        - ref: matrix_middle_num
          shift: [-hpx, hpy]
        - ref: matrix_inner_num # Upper-right corner, adding space for electronics
          shift: [2px + 3, py - 3.5]
        - ref: thumbs_extra_cluster # Bottmo of thumb cluster bump
          shift: [py - 7, -hpx - 2]
        - ref: thumbs_extra_cluster # Inside cluster
          shift: [-0.75py - 3, -hpx - 2]
        - ref: matrix_index_mod
          shift: [-px + 2, -hpy]
        - ref: matrix_ring_mod
          shift: [-hpx, -hpy]
        - ref: matrix_outer_bottom
          shift: [-0.75px, -hpy]
  battery_notch: #Cutout for larger battery wires to pass through
    - what: rectangle
      size: [5, 5]
      where: 
        ref: matrix_inner_top
        shift: [1.5px + 10.5, -7]
    - what: circle
      radius: 2.5
      where:
        ref: matrix_inner_top
        shift: [1.5px + 8, -7]
  big_battery_outline:
    - what: rectangle
      size: [36, 55]
      where:
        ref: matrix_inner_bottom
        shift: [px, -1]
  pcb:
    - name: board
    - operation: subtract
      name: battery_notch
  board_keycaps: # Mostly just for visualization
    - name: pcb
    - operation: subtract
      name: keys
  board_switch_cutouts: # Used to show where switches will go. Useful for 3D Printing.
    - name: pcb
    - operation: subtract
      name: switch_grid
  board_battery_position:
    - name: board_switch_cutouts
    - operation: subtract
      name: big_battery_outline
pcbs:
  # Working on a new reversible design
  reversible:
    template: kicad8
    outlines:
      main:
        outline: pcb
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2  
        where: /^(?:matrix|thumbs)_.*/
        params:
          side: B
          reversible: true
          hotswap: true
          solder: true
          include_keycap: true
          include_corner_marks: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: /^(?:matrix|thumbs)_.*/
        params:
          reversible: true
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 90
          shift: [8.5, -4]
      #TODO: Add options for rotary dial, scrollwheel, and choc switch here.
      rotary:
        # what: rotary
        what: EVQWGD001 # I decided I like this better.
        params:
          from: P7
          to: OPTION
          reverse: true
          A: P1
          B: GND
          C: P0
          D: unused
        where:
          ref: matrix_inner_home
          shift: [rotary_shift_x, rotary_shift_y]
          rotate: 0
      option_diode: # Separate diode for the rotary push-button
        what: ceoloide/diode_tht_sod123
        params:
          reversible: true
          include_tht: true
          from: OPTION
          to: P21
        where:
          ref: matrix_inner_home
          shift: [rotary_diode_shift_x, rotary_diode_shift_y]
          rotate: 180
      # Controller
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          side: F
          reversible: true
          reverse_mount: false # Nice!Nano chips face the shield
          include_traces: true
          include_extra_pins: false # Whether to include P101, P102, and P107 pin holes
          only_required_jumpers: false
          use_rectangular_jumpers: false # use chevron jumpers by default
          show_instructions: true
          show_silk_labels: true
          show_silk_labels_on_both_sides: true
          show_via_labels: true
          # via_size: 0.8
          # via_drill: 0.4
        where:
          ref: matrix_inner_top
          shift: [nice_nano_shift_x, nice_nano_shift_y]
          rotate: 0
      # Screen
      nice_view: 
        what: ceoloide/display_nice_view
        params:
          side: F
          reversible: true
          include_traces: true
          include_silkscreen: true
          include_courtyard: true
          CS: P2
          GND: GND
          VCC: VCC
          SCK: P3
          MOSI: P4
        where:
          ref: matrix_inner_top
          shift: [nice_view_shift_x, nice_view_shift_y]
          rotate: 0
      # Battery jack
      jstph:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          side: F
          reversible: true
          include_traces: true
          include_silkscreen: true
          include_fabrication: true
          include_courtyard: true
        where:
          ref: matrix_inner_top
          shift: [battery_shift_x, battery_shift_y]
          rotate: 0
      # Reset switch
      horizontal_reset:
        what: ceoloide/reset_switch_smd_side
        params:
          side: F
          reversible: true
          include_bosses: true
          include_silkscreen: true
          include_courtyard: true
        where:
          ref: matrix_inner_num
          shift: [reset_shift_x, reset_shift_y]
          rotate: 0
      # Switch
      battery_switch:
        what: ceoloide/power_switch_smd_side
        params:
          side: F
          reversible: true
          invert_behavior: false
          include_silkscreen: true
          include_courtyard: true
        where:
          ref: matrix_inner_top
          shift: [switch_shift_x, switch_shift_y]
          rotate: 0
      # PCB text - CYBERFOX
      cyberfox_text: 
        what: ceoloide/utility_text
        params: 
          # reversible: true
          text: "CYBERFOX-60"
          align: 'left'
          side: 'F'
          bold: true
          height: 2
          width: 2
          face: 'Hack Nerd Font' # Comment out if Hack NF not installed
        where: 
          ref: matrix_inner_bottom
          shift: [-hpx, -hpy - 1]
      creator_text:
        what: ceoloide/utility_text
        params:
          # reversible: true
          text: "Designed by Daniel Fox."
          align: 'left'
          side: 'F'
          bold: false
          height: 1
          width: 1
          face: 'Hack Nerd Font'
        where:
          ref: matrix_inner_bottom
          shift: [-hpx + 0.25, -hpy - 3]
      license_text:
        what: ceoloide/utility_text
        params:
          # reversible: true
          text: "Licensed under the GNU GPLv3."
          align: 'left'
          side: 'F'
          bold: false
          height: 1
          width: 1
          face: 'Hack Nerd Font'
        where:
          ref: matrix_inner_bottom
          shift: [-hpx + 0.25, -hpy - 4.5]
      cyberfox_text_r: 
        what: ceoloide/utility_text
        params: 
          # reversible: true
          text: "CYBERFOX-60"
          align: 'right'
          side: 'B'
          mirrored: true
          bold: true
          height: 2
          width: 2
          face: 'Hack Nerd Font' # Comment out if Hack NF not installed
        where: 
          ref: matrix_inner_bottom
          shift: [-hpx + 0.25, -hpy - 1]
      creator_text_r:
        what: ceoloide/utility_text
        params:
          # reversible: true
          text: "Designed by Daniel Fox."
          align: 'right'
          side: 'B'
          mirrored: true
          bold: false
          height: 1
          width: 1
          face: 'Hack Nerd Font'
        where:
          ref: matrix_inner_bottom
          shift: [-hpx + 0.5, -hpy - 3]
      license_text_r:
        what: ceoloide/utility_text
        params:
          # reversible: true
          text: "Licensed under the GNU GPLv3."
          align: 'right'
          side: 'B'
          mirrored: true
          bold: false
          height: 1
          width: 1
          face: 'Hack Nerd Font'
        where:
          ref: matrix_inner_bottom
          shift: [-hpx + 0.5, -hpy - 4.5]
      waywayway_text:
        what: ceoloide/utility_text
        params:
          reversible: true
          text: "WayWayWay"
          bold: false
          height: 1
          width: 1
          face: 'Hack Nerd Font'
        where:
          ref: thumbs_space_cluster
          rotate: -90
          shift: [-hpx - 3, 0]
      hole0:
        what: ceoloide/mounting_hole_npth
        where:
          ref: thumbs_extra_cluster
          shift: [0.75px, 0]
      hole1:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_inner_bottom
          shift: [1.5px, 0]
      hole2:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_index_num
          shift: [hpx + 2, hpy - 1]
      hole3:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_outer_num
          shift: [hpx + 1.5, 0]
      hole4:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_outer_bottom
          shift: [hpx + 1.5, 0]
      hole5:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_middle_home
          shift: [hpx - 0.5, hpy - 1]
      hole6:
        what: ceoloide/mounting_hole_npth
        where:
          ref: matrix_index_mod
          shift: [0, -hpy - 2]
