meta:
  engine: 4.1.0
  version: 0.5.0
  author: Daniel Fox
units:
  # For Ergogen - set the default width and height to Choc.
  # Comment out if you're using MX layout, though this only affects the display
  # on the Ergogen site.
  $default_width: cx
  $default_height: cy
  # Proxy spacing variables - Choc (low-profile)
  kx: cx
  ky: cy
  # Proxy spacing variables - MX layout
  # kx: u
  # ky: u
  # Padding
  px: kx + 2
  py: ky + 2
  # Half distance, for movement
  hx: (kx / 2)
  hy: (ky / 2)
  # half padding distance, for movement
  hpx: (px / 2)
  hpy: (py / 2)
  # positioning of electric components
  rotary_shift_x: px - 2
  rotary_shift_y: -hpy
  nice_nano_shift_x: px
  nice_nano_shift_y: hpy - 1
  nice_view_shift_x: px
  nice_view_shift_y: -hpy
  battery_shift_x: 1.5px - 3
  battery_shift_y: -hpy - 1
  reset_shift_x: 1.5px - 2
  reset_shift_y: hpy - 4
  switch_shift_x: 1.5px - 2
  switch_shift_y: -4
  text_shift_x: -hpx + 1
  text_shift_y: -hpy - 2
points:
  zones:
    matrix:
      anchor:
        shift: [100, -100] # correct anchoring for KiCAD sheet
      key:
        padding: 1ky
        spread: 1kx
        tags:
          cap: true
      rows:
        mod:
          row_net: P113
        bottom:
          row_net: P115
        home:
          row_net: P002
        top:
          row_net: P029
        num:
          row_net: P031
      columns:
        outer:
          rows.mod.skip: true
          key:
            width: 1.5kx
            stagger: 0
            col_net: P011
            tags:
              cap: false
              bigcap: true
        pinky:
          rows.mod.skip: true
          key:
            stagger: 0
            col_net: P104
            spread: 1.25kx
        ring:
          rows.mod.col_net: P104
          key:
            stagger: 5
            col_net: P106
        middle:
          rows.mod.col_net: P106
          key:
            stagger: 3
            col_net: P111
        index:
          rows.mod.col_net: P111
          key:
            stagger: -3
            col_net: P010
        inner:
          rows.mod.skip: true
          key:
            stagger: -3
            col_net: P009
    thumbs:
      key:
        spread: 1ky
        rotate: 90
        tags:
          bigcap: true
      anchor:
        ref: matrix_inner_mod
        shift: [2, -2]
      columns:
        space:
          key:
            height: 1.5kx
            splay: -30
            col_net: P010
            shift: [0.25hpx, -0.75hpy]
        extra:
          key:
            height: 1.5kx
            col_net: P009
            shift: [0.25hpx, -0.75hpy]
      rows:
        cluster:
          row_net: P113
  rotate: 0
  mirror: &mirror
    ref: thumbs_extra_cluster
    distance: 2.5kx
outlines:
  switch_grid:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  keys1u:
    - what: rectangle
      where: cap
      size: [kx-0.5, ky-0.5]
  keys15u:
    - what: rectangle
      where: bigcap
      size: [1.5kx-0.5, ky-0.5]
  keys:
    [keys1u, keys15u]
  board_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_num # Upper-left corner
          shift: [-0.75px, hpy]
        - ref: matrix_middle_num
          shift: [-hpx, hpy]
        - ref: matrix_middle_num
          shift: [hpx, hpy]
        - ref: matrix_inner_num
          shift: [hpx, hpy]
        - ref: matrix_inner_num # Upper-right corner, adding space for electronics
          shift: [hpx + 1px, hpy]
        - ref: thumbs_extra_cluster # Bottmo of thumb cluster bump
          shift: [0.75py, -hpy]
        - ref: thumbs_extra_cluster # Inside cluster
          shift: [-0.75py - 1, -hpx]
        - ref: matrix_ring_mod
          shift: [px - 2, -hpy]
        - ref: matrix_ring_mod
          shift: [-hpx, -hpy]
        - ref: matrix_outer_bottom
          shift: [-0.75px, -hpy]
  board_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_outer_num # Upper-left corner
          shift: [-0.75px, hpy]
        - ref: mirror_matrix_middle_num
          shift: [-hpx, hpy]
        - ref: mirror_matrix_middle_num
          shift: [hpx, hpy]
        - ref: mirror_matrix_inner_num
          shift: [hpx, hpy]
        - ref: mirror_matrix_inner_num # Upper-right corner, adding space for electronics
          shift: [hpx + 1px, hpy]
        - ref: mirror_thumbs_extra_cluster # Bottmo of thumb cluster bump
          shift: [0.75py, -hpy]
        - ref: mirror_thumbs_extra_cluster # Inside cluster
          shift: [-0.75py - 1, -hpx]
        - ref: mirror_matrix_ring_mod
          shift: [px - 2, -hpy]
        - ref: mirror_matrix_ring_mod
          shift: [-hpx, -hpy]
        - ref: mirror_matrix_outer_bottom
          shift: [-0.75px, -hpy]
  board_left_keycaps: # Mostly just for visualization
    - name: board_left
    - operation: subtract
      name: keys
  board_right_keycaps: # Mostly just for visualization
    - name: board_right
    - operation: subtract
      name: keys
  board_left_switch_cutouts: # Used to show where switches will go. Useful for 3D Printing.
    - name: board_left
    - operation: subtract
      name: switch_grid
  board_right_switch_cutouts: # Used to show where switches will go.  Useful for 3D Printing.
    - name: board_right
    - operation: subtract
      name: switch_grid
pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^(?:matrix|thumbs)_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^(?:matrix|thumbs)_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      rotary:
        # what: rotary
        what: scrollwheel # I decided I like this better.
        params:
          from: P011
          to: P113
          A: P006
          B: GND
          C: P008
          D: unused
        where:
          ref: matrix_inner_home
          shift: [rotary_shift_x, rotary_shift_y]
          rotate: 90
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_inner_top
          shift: [nice_nano_shift_x, nice_nano_shift_y]
          rotate: -90
      # Screen
      nice_view: 
        what: nice_view
        params:
          SDA: P017
          SCL: P020
          CS: P022
        where:
          ref: matrix_inner_top
          shift: [nice_view_shift_x, nice_view_shift_y]
          rotate: 90
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_inner_bottom
          shift: [battery_shift_x, battery_shift_y]
          rotate: 0
        params:
          side: B
          pos: POS
          neg: GND
      # Reset switch
      horizontal_reset:
        what: EVQPUC
        params:
          side: F
          from: GND
          to: RST
        where:
          ref: matrix_inner_bottom
          shift: [reset_shift_x, reset_shift_y]
          rotate: -90
      # Switch
      battery_switch:
        what: slider
        where:
          ref: matrix_inner_bottom
          shift: [switch_shift_x, switch_shift_y]
          rotate: -90
        params:
          side: F
          from: POS
          to: RAW
      # PCB text - CYBERFOX
      front_text: &text
        what: text
        where: &textWhere
          ref: matrix_inner_bottom
          shift: [-hpx + 1, -hpy - 2]
        params: &textParams
          text: "CYBERFOX-60"
          justify: left
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4
  right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^mirror_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^mirror_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      rotary:
        # what: rotary
        what: scrollwheel # I decided I like this better.
        params:
          from: P011
          to: P113
          A: P006
          B: GND
          C: P008
          D: unused
        where:
          ref: mirror_matrix_inner_home
          shift: [rotary_shift_x, rotary_shift_y]
          rotate: 270
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_inner_top
          shift: [nice_nano_shift_x, nice_nano_shift_y]
          rotate: -270
      # Screen
      nice_view: 
        what: nice_view
        params:
          SDA: P017
          SCL: P020
          CS: P022
        where:
          ref: mirror_matrix_inner_top
          shift: [nice_view_shift_x, nice_view_shift_y]
          rotate: 270
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_inner_bottom
          shift: [battery_shift_x, battery_shift_y]
          rotate: 0
        params:
          side: F
          pos: POS
          neg: GND
      # Reset switch
      horizontal_reset:
        what: EVQPUC
        params:
          side: F
          from: GND
          to: RST
        where:
          ref: mirror_matrix_inner_bottom
          shift: [reset_shift_x, reset_shift_y]
          rotate: -90
      # Switch
      battery_switch:
        what: slider
        where:
          ref: mirror_matrix_inner_bottom
          shift: [switch_shift_x, switch_shift_y]
          rotate: -90
        params:
          side: F
          from: POS
          to: RAW
      # PCB text - CYBERFOX
      front_text: &text
        what: text
        where: &textWhere
          ref: mirror_matrix_inner_bottom
          shift: [text_shift_x, text_shift_y]
        params: &textParams
          text: "CYBERFOX-60"
          justify: right
          h_size: 3.0
          v_size: 3.0
          thickness: 0.4
